 version: 2

 build:
   os: "ubuntu-24.04"
   tools:
     python: "3"
   # We recommend using a requirements file for reproducible builds. TODO
   # This is just a quick example to get started.
   # https://docs.readthedocs.io/page/guides/reproducible-builds.html
   jobs:
     pre_install:
       - pip install mkdocs-material
       - pip install mkapi

 mkdocs:
   configuration: docs/mkdocs.yml