services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data_tmp
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=warehouse


## In case of errors with architecture: 
# docker compose down --volumes
# docker image rm postgres:17
# docker compose pull
# docker compose up
