site_name: End to End ML pipeline for profiling insurance customers
# 
site_author: XRD Group
# 

theme:
  name: material

nav:
  - Home: index.md
  - API Reference:
    - $api/policyML.***

plugins: 
  - search
  - mkapi
