name: Python Package using Conda

on: 
  pull_request:
  push:
      branches: [main]
      paths:
        - ".github/workflows/*"
        - "policyML/**"
        - "tests/**"
        - "Makefile"
        - "pyproject.toml"
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda with Python 3.12
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12
        activate-environment: ml-pipeline-insurance-customer
        auto-activate-base: false
        auto-update-conda: true

    - name: Install dependencies from pyproject.toml
      run: |
        pip install --upgrade pip
        pip install .  # install your package and dependencies
        pip install pytest ruff  # install testing and linting tools

    - name: Lint with Ruff
      run: |
        ruff check . --exit-code 1

    - name: Run tests
      run: |
        pytest
